### ISSUE TITLE
Unable to build golang qt bindings using this tool

### ISSUE THREAD

**Issue by jhgarner** [tweag/gomod2nix#15]
**Describe the bug**
Attempting to use gomod2nix to build https://github.com/therecipe/qt fails. The gomod2nix.toml file is generated successfully, but the buildGoApplication run hits an error:
```
Building subPackage ./cmd/env
cmd/env/linux_amd64.go:5:8: cannot find package "." in:
        /build/source/vendor/github.com/therecipe/env_linux_amd64_513
```

**To Reproduce**
run nix-build on the attached default.nix file with the gomod2nix.toml in the same directory. Nix fails to build the cmd/env subpackage.

<details><summary>default.nix and gomod2nix.toml files</summary>
<p>
default.nix:

```nix
let
  pkgs = import <nixpkgs> {};

  gomod2nixSrc = pkgs.fetchFromGitHub {
    owner = "tweag";
    repo = "gomod2nix";
    rev = "67f22dd738d092c6ba88e420350ada0ed4992ae8";
    sha256 = "0a9rhw6djgcrky5nzly3srsl8095q42f2nyzxyisp9fh9fg70nih";
  };
  buildGoApplication = pkgs.callPackage "${gomod2nixSrc}/builder/default.nix" {};

  goqtSource = pkgs.fetchFromGitHub {
    owner = "therecipe";
    repo = "qt";
    rev = "c0c124a5770d357908f16fa57e0aa0ec6ccd3f91";
    sha256 = "197wdh2v0g5g2dpb1gcd5gp0g4wqzip34cawisvy6z7mygmsc8rd";
  };

  goqtToml = ./gomod2nix.toml;

  goqt = buildGoApplication rec {
    pname = "go-qt";
    version = "c0c124a5770d357908f16fa57e0aa0ec6ccd3f91";
    src = goqtSource;
    modules = goqtToml;
  };
in
  goqt
```

gomod2nix.toml:

```toml
["github.com/davecgh/go-spew"]
  sumVersion = "v1.1.1"
  ["github.com/davecgh/go-spew".fetch]
    type = "git"
    url = "https://github.com/davecgh/go-spew"
    rev = "8991bc29aa16c548c550c7ff78260e27b9ab7c73"
    sha256 = "0hka6hmyvp701adzag2g26cxdj47g21x6jz4sc6jjz1mn59d474y"

["github.com/gopherjs/gopherjs"]
  sumVersion = "v0.0.0-20190411002643-bd77b112433e"
  ["github.com/gopherjs/gopherjs".fetch]
    type = "git"
    url = "https://github.com/gopherjs/gopherjs"
    rev = "bd77b112433e999447bf4bc599e36214ba494a99"
    sha256 = "0bsj69jb0glfvqhqld4c78840iagd0iy2b92878i5w4sgp40k7i1"

["github.com/konsorten/go-windows-terminal-sequences"]
  sumVersion = "v1.0.2"
  ["github.com/konsorten/go-windows-terminal-sequences".fetch]
    type = "git"
    url = "https://github.com/konsorten/go-windows-terminal-sequences"
    rev = "f55edac94c9bbba5d6182a4be46d86a2c9b5b50e"
    sha256 = "09mn209ika7ciy87xf2x31dq5fnqw39jidgaljvmqxwk7ff1hnx7"

["github.com/pmezard/go-difflib"]
  sumVersion = "v1.0.0"
  ["github.com/pmezard/go-difflib".fetch]
    type = "git"
    url = "https://github.com/pmezard/go-difflib"
    rev = "792786c7400a136282c1664665ae0a8db921c6c2"
    sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw"

["github.com/sirupsen/logrus"]
  sumVersion = "v1.4.1"
  ["github.com/sirupsen/logrus".fetch]
    type = "git"
    url = "https://github.com/sirupsen/logrus"
    rev = "8bdbc7bcc01dcbb8ec23dc8a28e332258d25251f"
    sha256 = "1m7ny9jkb98cxqhsp13xa5hnqh1s9f25x04q6arsala4zswsw33c"

["github.com/stretchr/objx"]
  sumVersion = "v0.2.0"
  ["github.com/stretchr/objx".fetch]
    type = "git"
    url = "https://github.com/stretchr/objx"
    rev = "ea4fe68685ee0d3cee7032121851b57e7494e8ea"
    sha256 = "0pcdvakxgddaiwcdj73ra4da05a3q4cgwbpm2w75ycq4kzv8ij8k"

["github.com/stretchr/testify"]
  sumVersion = "v1.3.0"
  ["github.com/stretchr/testify".fetch]
    type = "git"
    url = "https://github.com/stretchr/testify"
    rev = "ffdc059bfe9ce6a4e144ba849dbedead332c6053"
    sha256 = "0wjchp2c8xbgcbbq32w3kvblk6q6yn533g78nxl6iskq6y95lxsy"

["golang.org/x/crypto"]
  sumVersion = "v0.0.0-20190418165655-df01cb2cc480"
  vendorPath = "github.com/golang/crypto"
  ["golang.org/x/crypto".fetch]
    type = "git"
    url = "https://github.com/golang/crypto"
    rev = "df01cb2cc480549d72034218dd98bf97671450ac"
    sha256 = "1fhz0rym06j0fds0wg8xf6i9mm37m6qgdv83qxfh3nh0mgzf19qs"

["golang.org/x/net"]
  sumVersion = "v0.0.0-20190420063019-afa5a82059c6"
  vendorPath = "github.com/golang/net"
  ["golang.org/x/net".fetch]
    type = "git"
    url = "https://github.com/golang/net"
    rev = "afa5a82059c6356159f699d81beff22a81842231"
    sha256 = "1zhcr1m7n550m0lqjqg1rl2qrnghkl3a25vcm6cgpiqvk89f8lba"

["golang.org/x/sys"]
  sumVersion = "v0.0.0-20190419153524-e8e3143a4f4a"
  vendorPath = "github.com/golang/sys"
  ["golang.org/x/sys".fetch]
    type = "git"
    url = "https://github.com/golang/sys"
    rev = "e8e3143a4f4a00f1fafef0dd82ba78223281b01b"
    sha256 = "02pdj4gr658r99kqwxy6v4lb8w2h0zaiqq1jyqrsxqiyapijhw87"

["golang.org/x/text"]
  sumVersion = "v0.3.1-0.20190410012825-f4905fbd45b6"
  vendorPath = "github.com/golang/text"
  ["golang.org/x/text".fetch]
    type = "git"
    url = "https://github.com/golang/text"
    rev = "f4905fbd45b6790792202848439271c74074bbfd"
    sha256 = "184d6ap2g92jvx0532lymdqbnx9vi9ips4dq5lnqbby0caccc6r1"

["golang.org/x/tools"]
  sumVersion = "v0.0.0-20190420181800-aa740d480789"
  vendorPath = "github.com/golang/tools"
  ["golang.org/x/tools".fetch]
    type = "git"
    url = "https://github.com/golang/tools"
    rev = "aa740d4807891cb493e9f727901baf334b9fabce"
    sha256 = "0431y2xw39dss0ldxhbmm7ip4d2cr2w9km2a5psgwan6v481kz0a"
```
</p></details>

**Expected behavior**
The package should build correctly.

**Environment**
 - OS name + version: Nixos unstable
 - Version of the code: 67f22dd738d092c6ba88e420350ada0ed4992ae8 (lastest commit)

**Additional context**
I have basically no experience with golang and even less packaging it with nix. I tried using the nixpkgs buildGoModule function but that didn't work in other ways. Some Googling led me to this package which appears to make it further in the process but still fails. The goal is to build https://github.com/akiyosi/goneovim which depends on the qt bindings.

The qt package seems to be pretty large and complicated so I'm not sure how to begin to debug this.
